### ISSUE TITLE
error while .check

### ISSUE THREAD

**Issue by ofcansh** [snowish1337/Sellix-Discord-Bot#1]
(node:112) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'order' of null
    at /home/runner/OlympusSellix/commands/sellix/CheckCommand.js:14:80
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Lleyton0201** [comment]
I have the same issue
